name: fuzzy_chat
description: End to End encripted chat, It's content is stored locally only and can be read only by chat members
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_links: ^7.0.0
  biometric_storage: ^5.0.1
  bloc: ^8.1.2
  desktop_drop: ^0.6.0
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dropzone: ^4.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: 2.13.0
  flutter_secure_storage: ^9.2.2
  fuzzy_crypto_core:
    path: rust_builder
  fuzzzy_ui_kit:
    git:
      url: https://github.com/fuzzzy-bot/fuzzy_design.git
      ref: f66d663b248c8dc87c93b54429247540a4343f87
  get_it: ^8.0.0
  go_router: ^13.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.4.0
  marionette_flutter: ^0.6.0
  path: ^1.9.0
  path_provider: ^2.0.11
  permission_handler: ^12.0.0
  pointycastle:
    path: packages/pointycastle
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vibration: ^2.0.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  marionette_mcp: ^0.6.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  # android: true
  # ios: true
  # remove_alpha_ios: true
  # windows:
  #   generate: true
  #   image_path: "assets/logo/f.webp"
  #   icon_size: 48
  # macos:
  #   generate: true
  #   image_path: "assets/logo/f.webp"
  # image_path: "assets/logo/f.webp"
