#!/usr/bin/env python3

"""
Fill this app's iOS app icon sets from the approved 1024 plates.

Why this exists instead of flutter_launcher_icons: for a flavour the package
writes to `AppIcon-<flavor>.appiconset`, while this project's build
configurations read `StagingAppIcon` / `DevelopmentAppIcon`, and the package
rewrites ASSETCATALOG_COMPILER_APPICON_NAME in the Xcode project while it runs
(a flavour-less run flattens all nine configurations onto `AppIcon`). So
Android is generated by flutter_launcher_icons and iOS is filled here.

Each icon set keeps its own `Contents.json` untouched: this script only reads
the size/scale pairs already declared there and rewrites those PNGs in place at
the right pixel size, opaque (an app icon with alpha is an App Store
rejection). The plates are the approved artwork and are never cropped, padded
or re-fitted — only resized.

Requires Pillow (`pip install Pillow`).

Examples
--------

# every environment, using the default mapping
python3 scripts/ios_app_icons.py

# one environment only
python3 scripts/ios_app_icons.py --only staging
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover - dependency hint
    sys.exit("Pillow is required: pip install Pillow")

APP_ROOT = Path(__file__).resolve().parent.parent

# environment -> (approved 1024 plate, the icon set that environment's build reads)
ENVIRONMENTS = {
    "production": (
        "assets/launcher_icons/production/ios/AppIcon-1024.png",
        "AppIcon",
    ),
    "staging": (
        "assets/launcher_icons/staging/ios/AppIcon-1024.png",
        "StagingAppIcon",
    ),
    "development": (
        "assets/launcher_icons/development/ios/AppIcon-1024.png",
        "DevelopmentAppIcon",
    ),
}

ASSETS = APP_ROOT / "ios" / "Runner" / "Assets.xcassets"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Resize the approved 1024 plates into the iOS app icon sets."
    )
    parser.add_argument(
        "--only",
        choices=sorted(ENVIRONMENTS),
        help="Fill a single environment instead of all three.",
    )
    return parser.parse_args()


def pixel_size(image: dict) -> int:
    """The pixel size Xcode expects for one declared entry.

    `expected-size` when the set carries it, otherwise the points in `size`
    multiplied by `scale` — e.g. 20x20 at 3x is 60px.
    """
    if "expected-size" in image:
        return int(float(image["expected-size"]))
    points = float(image["size"].split("x")[0])
    scale = float(image["scale"].rstrip("x"))
    return int(round(points * scale))


def fill(environment: str, plate_path: str, icon_set: str) -> None:
    plate = APP_ROOT / plate_path
    contents = ASSETS / f"{icon_set}.appiconset" / "Contents.json"
    if not plate.exists():
        sys.exit(f"missing plate: {plate}")
    if not contents.exists():
        sys.exit(f"missing icon set: {contents}")

    source = Image.open(plate).convert("RGB")
    declared = json.loads(contents.read_text())["images"]

    # one filename can be declared for several idiom/scale rows; write it once
    sizes: dict[str, int] = {}
    for image in declared:
        filename = image.get("filename")
        if filename:
            sizes[filename] = pixel_size(image)

    for filename, size in sorted(sizes.items(), key=lambda item: item[1]):
        target = contents.parent / filename
        source.resize((size, size), Image.LANCZOS).save(target, format="PNG")
        print(f"{environment}: {icon_set}.appiconset/{filename} -> {size}px")


def main() -> None:
    args = parse_args()
    chosen = [args.only] if args.only else list(ENVIRONMENTS)
    for environment in chosen:
        plate_path, icon_set = ENVIRONMENTS[environment]
        fill(environment, plate_path, icon_set)


if __name__ == "__main__":
    main()
