// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `opened_mut`, `opened`

/// Draws a fresh 32-byte store key and returns it wrapped under `password`
/// (0x10 blob — the only form the key ever takes outside Rust). Call
/// [`open_store`] with the blob to use it.
Future<Uint8List> createStoreKey({required String password}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiCoreCreateStoreKey(password: password);

/// Unwraps `wrapped` under `password` and opens the store at
/// `<store_dir>/fuzzy_crypto_store/` (created if missing). A wrong password —
/// or a tampered blob — is `WrongPassword`.
Future<CryptoCore> openStore(
        {required String storeDir,
        required List<int> wrapped,
        required String password}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiCoreOpenStore(
        storeDir: storeDir, wrapped: wrapped, password: password);

/// Re-wraps the store key under `new_password` with a fresh salt and nonce.
/// The old blob keeps opening with the old password until the caller replaces it.
Future<Uint8List> rewrapStoreKey(
        {required List<int> wrapped,
        required String oldPassword,
        required String newPassword}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiCoreRewrapStoreKey(
        wrapped: wrapped, oldPassword: oldPassword, newPassword: newPassword);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CryptoCore>>
abstract class CryptoCore implements RustOpaqueInterface {
  /// Drops the store key and every cached state (all zeroised on drop).
  Future<void> close();

  /// Overwrites the chat's state file with zeros (best effort), unlinks it
  /// and forgets the cached state.
  Future<void> deleteChat({required String chatId});

  /// Inverse of [`CryptoCore::seal_local`]; a tampered or foreign blob is `Corrupt`.
  Future<Uint8List> openLocal({required List<int> blob});

  /// Seals `bytes` for local storage (message history, F2-8) under the
  /// HKDF-derived local key: a 0x20 blob with a fresh random nonce.
  Future<Uint8List> sealLocal({required List<int> bytes});

  /// The directory the store was opened with (for tests).
  Future<String> storeDir();
}
