// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pairing.dart';

// These functions are ignored because they are not marked as `pub`: `opened_mut`, `opened`

/// Draws a fresh 32-byte store key and returns it wrapped under `password`
/// (0x10 blob — the only form the key ever takes outside Rust). Call
/// [`open_store`] with the blob to use it.
Future<Uint8List> createStoreKey({required String password}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiCoreCreateStoreKey(password: password);

/// Unwraps `wrapped` under `password` and opens the store at
/// `<store_dir>/fuzzy_crypto_store/` (created if missing). A wrong password —
/// or a tampered blob — is `WrongPassword`.
Future<CryptoCore> openStore(
        {required String storeDir,
        required List<int> wrapped,
        required String password}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiCoreOpenStore(
        storeDir: storeDir, wrapped: wrapped, password: password);

/// Re-wraps the store key under `new_password` with a fresh salt and nonce.
/// The old blob keeps opening with the old password until the caller replaces it.
Future<Uint8List> rewrapStoreKey(
        {required List<int> wrapped,
        required String oldPassword,
        required String newPassword}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiCoreRewrapStoreKey(
        wrapped: wrapped, oldPassword: oldPassword, newPassword: newPassword);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CryptoCore>>
abstract class CryptoCore implements RustOpaqueInterface {
  /// B (accepter): verifies A's invitation, establishes the outbound session
  /// on its one-time key and returns the signed acceptance as `Fuzz/` text.
  /// `chat_id` must be the one inside the invitation (`WrongChat` otherwise);
  /// a chat that already has state is `Internal`.
  Future<String> acceptInvitation(
      {required String chatId, required String invitation});

  /// `Connected` once this side holds a session, `Invited` before.
  Future<ChatStatus> chatStatus({required String chatId});

  /// Drops the store key and every cached state (all zeroised on drop).
  Future<void> close();

  /// A (inviter): verifies B's acceptance and completes the handshake —
  /// the one-time key is consumed exactly once, so a second acceptance for
  /// the same invitation is `InvitationAlreadyUsed`. The session is on disk
  /// before this returns; any failure leaves the chat untouched.
  Future<void> completeHandshake(
      {required String chatId, required String acceptance});

  /// A (inviter): creates the chat's Olm account and returns the signed
  /// invitation as `Fuzz/` text. Calling it again for a pending chat
  /// **regenerates** — a brand-new account replaces the old one, so the old
  /// invitation can no longer be completed. A connected chat is `Internal`.
  Future<String> createInvitation({required String chatId});

  /// The acceptance this chat last produced, for re-display.
  Future<String> currentAcceptance({required String chatId});

  /// The invitation this chat last produced, for re-display.
  Future<String> currentInvitation({required String chatId});

  /// Decrypts a pasted message blob against `chat_id`'s session, checking the
  /// inner header and the replay/ordering window in the fixed order of plan
  /// §B.4. On any failure nothing is persisted — the state file is untouched,
  /// so the message key stays available for a re-paste (plan §B.6). Replay →
  /// `Replay`, a gap beyond Olm's window → `TooOld`, a blob for another chat or
  /// with the wrong identities → `WrongChat`, anything malformed → `Corrupt`.
  Future<String> decryptText({required String chatId, required String blob});

  /// Overwrites the chat's state file with zeros (best effort), unlinks it
  /// and forgets the cached state.
  Future<void> deleteChat({required String chatId});

  /// Encrypts `text` on `chat_id`'s live Olm session and returns the `Fuzz/`
  /// message blob. The ratcheted session and the incremented send counter are
  /// persisted before the blob is returned, so a counter is never reused even
  /// across a crash. A chat that is not connected is `Internal`; an unknown
  /// chat id is `UnknownChat`.
  Future<String> encryptText({required String chatId, required String text});

  /// The persisted flag; `false` for every chat until [`CryptoCore::mark_verified`].
  Future<bool> isVerified({required String chatId});

  /// Persists whether the user compared the safety number with the peer. The
  /// flag is on disk before this returns; a chat that is not paired yet is
  /// `UnknownChat`.
  Future<void> markVerified({required String chatId, required bool verified});

  /// Inverse of [`CryptoCore::seal_local`]; a tampered or foreign blob is `Corrupt`.
  Future<Uint8List> openLocal({required List<int> blob});

  /// The chat's 60-digit safety number (`"12345 67890 …"`, 12 groups), derived
  /// from both Ed25519 identity keys and the chat id (plan §B.3) — identical on
  /// both sides of a pairing. `UnknownChat` for a chat the store does not know
  /// or that is not paired yet. Nothing secret is involved; it stays async
  /// like every other call on the handle.
  Future<String> safetyNumber({required String chatId});

  /// Seals `bytes` for local storage (message history, F2-8) under the
  /// HKDF-derived local key: a 0x20 blob with a fresh random nonce.
  Future<Uint8List> sealLocal({required List<int> bytes});

  /// The directory the store was opened with (for tests).
  Future<String> storeDir();
}
