// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `finished`, `run`, `running`

Future<FileJob> newFileJob() =>
    FuzzyCryptoCoreLib.instance.api.crateApiFilesNewFileJob();

/// Encrypts the file at `input` into the password-mode 0x04 container at
/// `output` (`.part` until the last chunk is written and fsynced), streaming
/// one [`FileProgress`] per 1 MiB chunk into `sink`. The file key is
/// Argon2id(password) with a fresh salt. Runs on frb's pool; the store must be
/// unlocked (`store locked` otherwise).
Stream<FileProgress> encryptFile(
        {required CryptoCore core,
        required String password,
        required String input,
        required String output,
        required FileJob job}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiFilesEncryptFile(
        core: core, password: password, input: input, output: output, job: job);

/// Decrypts the password-mode container at `input` to `output`, writing each
/// chunk to `<output>.part` only after its tag verified and renaming at the
/// end; on any failure or cancel the `.part` is removed and no output exists.
/// Failure text: `wrong password` (chunk 0 does not open), `corrupt` (a later
/// chunk, a truncation or appended bytes), `unsupported format` (not a
/// password-mode container).
Stream<FileProgress> decryptFile(
        {required CryptoCore core,
        required String password,
        required String input,
        required String output,
        required FileJob job}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiFilesDecryptFile(
        core: core, password: password, input: input, output: output, job: job);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FileJob>>
abstract class FileJob implements RustOpaqueInterface {
  /// Terminal: the loop unlinks `<output>.part` and emits `is_cancelled` at
  /// the next chunk boundary (also while paused).
  void cancel();

  /// The loop finishes the chunk in flight, then sleeps 50 ms at a time until
  /// [`FileJob::resume`] or [`FileJob::cancel`].
  void pause();

  /// Continues a paused job at the next chunk boundary; a no-op otherwise.
  void resume();
}

/// One event of a file job — maps 1:1 onto the app's `FileProcessingProgress`.
///
/// `progress` is the fraction of chunks done (one event per chunk). The last
/// event is terminal: `is_complete` on success, `is_cancelled` after
/// [`FileJob::cancel`], or `is_complete` with an `error_message` (the
/// [`CoreError`]'s text: `wrong password`, `corrupt`, `unsupported format`,
/// `io`, `store locked`, `internal`) on failure — no `Err` ever reaches Dart,
/// because frb does not await a stream function's result (`unawaited`).
class FileProgress {
  final double progress;
  final bool isComplete;
  final bool isCancelled;
  final String? errorMessage;

  const FileProgress({
    required this.progress,
    required this.isComplete,
    required this.isCancelled,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      progress.hashCode ^
      isComplete.hashCode ^
      isCancelled.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileProgress &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          isComplete == other.isComplete &&
          isCancelled == other.isCancelled &&
          errorMessage == other.errorMessage;
}
