// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Classifies a pasted blob without touching any key material.
BlobType blobTypeOf({required String text}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiFormatsBlobTypeOf(text: text);

/// The clear chat id of a pasted invitation or acceptance — the only two blobs
/// that carry one. Anything else is `UnsupportedFormat`; a malformed payload is `Corrupt`.
///
/// A routing hint only: nothing is authenticated here. `accept_invitation` /
/// `complete_handshake` verify the signature and re-check the chat id before
/// the blob touches any state.
String peekChatId({required String text}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiFormatsPeekChatId(text: text);

/// What a pasted `Fuzz/` string is, judged by its outer envelope alone.
///
/// `unknown` covers everything the paste path must refuse: no `Fuzz/` prefix,
/// bad base64url, unknown magic/version/type, and the storage-only kinds
/// (wrapped store key, local seal).
enum BlobType {
  invitation,
  acceptance,
  message,
  file,
  passwordSealed,
  unknown,
  ;
}
