// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The crate version, so Dart can prove the bridge is alive.
Future<String> coreVersion() =>
    FuzzyCryptoCoreLib.instance.api.crateApiHealthCoreVersion();

/// Reverses `bytes` — a trivial round trip that proves byte vectors cross the FFI intact.
Future<Uint8List> roundTrip({required List<int> bytes}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiHealthRoundTrip(bytes: bytes);
