// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Seals `text` under `password` as a paste-able `Fuzz/` string (0x05 blob:
/// Argon2id m=65536 t=4 p=1 recorded in the header, XChaCha20-Poly1305 with
/// the header as AAD). Every call draws a fresh salt and nonce.
Future<String> passwordSealText(
        {required String password, required String text}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiPasswordsPasswordSealText(password: password, text: text);

/// Inverse of [`password_seal_text`]; whitespace from wrapping is ignored.
/// A wrong password and a tampered blob are both `WrongPassword` (the AEAD
/// cannot tell them apart); anything that is not a 0x05 is `UnsupportedFormat`.
Future<String> passwordOpenText(
        {required String password, required String blob}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiPasswordsPasswordOpenText(password: password, blob: blob);

/// [`password_seal_text`] for arbitrary bytes, as the binary 0x05 blob (the
/// vault's optional custom-password layer).
Future<Uint8List> passwordSealBytes(
        {required String password, required List<int> bytes}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiPasswordsPasswordSealBytes(password: password, bytes: bytes);

/// Inverse of [`password_seal_bytes`]; the same error rules as [`password_open_text`].
Future<Uint8List> passwordOpenBytes(
        {required String password, required List<int> blob}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiPasswordsPasswordOpenBytes(password: password, blob: blob);
