// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `unlocked`

/// Draws a fresh master key and wraps it under `password`. Password strength
/// is the app's judgement, not this function's.
Future<VaultInitResult> vaultInit({required String password}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiVaultVaultInit(password: password);

/// Unwraps the master key; a wrong password (or a tampered blob) is `WrongPassword`.
Future<VaultKey> vaultUnlock(
        {required String password, required List<int> wrapped}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiVaultVaultUnlock(password: password, wrapped: wrapped);

/// Re-wraps the same master key under `new_password` (fresh salt and nonce).
/// Because the key does not change, no vault item needs re-encryption; the
/// caller replaces the stored blob and keeps every item as it is.
Future<Uint8List> vaultRewrap(
        {required String oldPassword,
        required String newPassword,
        required List<int> wrapped}) =>
    FuzzyCryptoCoreLib.instance.api.crateApiVaultVaultRewrap(
        oldPassword: oldPassword, newPassword: newPassword, wrapped: wrapped);

/// Seals one item under the master key: a 0x20 blob with a fresh nonce and
/// AAD `vault-item`.
Future<Uint8List> vaultSeal(
        {required VaultKey key, required List<int> bytes}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiVaultVaultSeal(key: key, bytes: bytes);

/// Inverse of [`vault_seal`]; a tampered or foreign blob is `Corrupt`.
Future<Uint8List> vaultOpen({required VaultKey key, required List<int> blob}) =>
    FuzzyCryptoCoreLib.instance.api
        .crateApiVaultVaultOpen(key: key, blob: blob);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultKey>>
abstract class VaultKey implements RustOpaqueInterface {
  /// Drops the master key (zeroised). Later `vault_seal`/`vault_open` calls
  /// on this handle answer `StoreLocked`; a second `close` is a no-op.
  Future<void> close();
}

/// What [`vault_init`] hands back: the unlocked key and its wrapping, which
/// the app stores in the vault metadata and feeds to [`vault_unlock`] later.
/// `non_opaque` so frb passes the two fields once instead of wrapping the
/// struct in a second handle with a cloning accessor for the key.
class VaultInitResult {
  final VaultKey key;

  /// A 0x10 blob — the master key wrapped under the vault password.
  final Uint8List wrapped;

  const VaultInitResult({
    required this.key,
    required this.wrapped,
  });

  @override
  int get hashCode => key.hashCode ^ wrapped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultInitResult &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          wrapped == other.wrapped;
}
