// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Every error the crypto core reports to Dart (plan §B.4, §B.7).
///
/// Exhaustive by design: frb translates it into a Dart `enum` the service maps
/// onto its own failures. Add a variant only when a feature needs one — never a
/// catch-all string for a case that already has a variant.
///
/// Every variant is payload-free on purpose: frb 2.13 emits a data-carrying enum
/// as a `freezed` sealed class, and `freezed` is not a dependency this app carries
/// (plan §7). The OS message of an `Io` failure therefore stays on the Rust side.
enum CoreError {
  /// Unknown magic, version, type byte or text encoding — not a blob this build reads.
  unsupportedFormat,

  /// An Ed25519 signature over an invitation or acceptance did not verify.
  invalidSignature,

  /// The invitation's one-time key has already been consumed.
  invitationAlreadyUsed,

  /// The blob belongs to a different chat than the one it was pasted into.
  wrongChat,

  /// The blob was already decrypted once.
  replay,

  /// The blob's counter fell out of the acceptance window.
  tooOld,

  /// The bytes are structurally invalid or fail authentication.
  corrupt,

  /// The password does not open the store, vault or blob.
  wrongPassword,

  /// The store has not been opened (or was closed) in this process.
  storeLocked,

  /// No state exists for the requested chat id.
  unknownChat,

  /// A file-system operation failed.
  io,

  /// A file job was cancelled by the user.
  cancelled,

  /// An invariant the core relies on did not hold.
  internal,
  ;
}
