// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/files.dart';
import 'api/formats.dart';
import 'api/health.dart';
import 'api/pairing.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class FuzzyCryptoCoreLib extends BaseEntrypoint<FuzzyCryptoCoreLibApi,
    FuzzyCryptoCoreLibApiImpl, FuzzyCryptoCoreLibWire> {
  @internal
  static final instance = FuzzyCryptoCoreLib._();

  FuzzyCryptoCoreLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    FuzzyCryptoCoreLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required FuzzyCryptoCoreLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<FuzzyCryptoCoreLibApiImpl, FuzzyCryptoCoreLibWire>
      get apiImplConstructor => FuzzyCryptoCoreLibApiImpl.new;

  @override
  WireConstructor<FuzzyCryptoCoreLibWire> get wireConstructor =>
      FuzzyCryptoCoreLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 638624754;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'fuzzy_crypto_core',
    ioDirectory: 'rust/fuzzy_crypto_core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class FuzzyCryptoCoreLibApi extends BaseApi {
  Future<String> crateApiCoreCryptoCoreAcceptInvitation(
      {required CryptoCore that,
      required String chatId,
      required String invitation});

  Future<ChatStatus> crateApiCoreCryptoCoreChatStatus(
      {required CryptoCore that, required String chatId});

  Future<void> crateApiCoreCryptoCoreClose({required CryptoCore that});

  Future<void> crateApiCoreCryptoCoreCompleteHandshake(
      {required CryptoCore that,
      required String chatId,
      required String acceptance});

  Future<String> crateApiCoreCryptoCoreCreateInvitation(
      {required CryptoCore that, required String chatId});

  Future<String> crateApiCoreCryptoCoreCurrentAcceptance(
      {required CryptoCore that, required String chatId});

  Future<String> crateApiCoreCryptoCoreCurrentInvitation(
      {required CryptoCore that, required String chatId});

  Future<String> crateApiCoreCryptoCoreDecryptText(
      {required CryptoCore that, required String chatId, required String blob});

  Future<void> crateApiCoreCryptoCoreDeleteChat(
      {required CryptoCore that, required String chatId});

  Future<String> crateApiCoreCryptoCoreEncryptText(
      {required CryptoCore that, required String chatId, required String text});

  Future<bool> crateApiCoreCryptoCoreIsVerified(
      {required CryptoCore that, required String chatId});

  Future<void> crateApiCoreCryptoCoreMarkVerified(
      {required CryptoCore that,
      required String chatId,
      required bool verified});

  Future<Uint8List> crateApiCoreCryptoCoreOpenLocal(
      {required CryptoCore that, required List<int> blob});

  Future<String> crateApiCoreCryptoCoreSafetyNumber(
      {required CryptoCore that, required String chatId});

  Future<Uint8List> crateApiCoreCryptoCoreSealLocal(
      {required CryptoCore that, required List<int> bytes});

  Future<String> crateApiCoreCryptoCoreStoreDir({required CryptoCore that});

  void crateApiFilesFileJobCancel({required FileJob that});

  void crateApiFilesFileJobPause({required FileJob that});

  void crateApiFilesFileJobResume({required FileJob that});

  BlobType crateApiFormatsBlobTypeOf({required String text});

  Future<String> crateApiHealthCoreVersion();

  Future<Uint8List> crateApiCoreCreateStoreKey({required String password});

  Stream<FileProgress> crateApiFilesDecryptFile(
      {required CryptoCore core,
      required String password,
      required String input,
      required String output,
      required FileJob job});

  Stream<FileProgress> crateApiFilesEncryptFile(
      {required CryptoCore core,
      required String password,
      required String input,
      required String output,
      required FileJob job});

  Future<FileJob> crateApiFilesNewFileJob();

  Future<CryptoCore> crateApiCoreOpenStore(
      {required String storeDir,
      required List<int> wrapped,
      required String password});

  String crateApiFormatsPeekChatId({required String text});

  Future<Uint8List> crateApiCoreRewrapStoreKey(
      {required List<int> wrapped,
      required String oldPassword,
      required String newPassword});

  Future<Uint8List> crateApiHealthRoundTrip({required List<int> bytes});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CryptoCore;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CryptoCore;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CryptoCorePtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_FileJob;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_FileJob;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_FileJobPtr;
}

class FuzzyCryptoCoreLibApiImpl extends FuzzyCryptoCoreLibApiImplPlatform
    implements FuzzyCryptoCoreLibApi {
  FuzzyCryptoCoreLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCoreCryptoCoreAcceptInvitation(
      {required CryptoCore that,
      required String chatId,
      required String invitation}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_String(invitation, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreAcceptInvitationConstMeta,
      argValues: [that, chatId, invitation],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreAcceptInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_accept_invitation",
        argNames: ["that", "chatId", "invitation"],
      );

  @override
  Future<ChatStatus> crateApiCoreCryptoCoreChatStatus(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_chat_status,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreChatStatusConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreChatStatusConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_chat_status",
        argNames: ["that", "chatId"],
      );

  @override
  Future<void> crateApiCoreCryptoCoreClose({required CryptoCore that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreCryptoCoreCloseConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreCloseConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_close",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiCoreCryptoCoreCompleteHandshake(
      {required CryptoCore that,
      required String chatId,
      required String acceptance}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_String(acceptance, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreCompleteHandshakeConstMeta,
      argValues: [that, chatId, acceptance],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreCompleteHandshakeConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_complete_handshake",
        argNames: ["that", "chatId", "acceptance"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreCreateInvitation(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreCreateInvitationConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreCreateInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_create_invitation",
        argNames: ["that", "chatId"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreCurrentAcceptance(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreCurrentAcceptanceConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreCurrentAcceptanceConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_current_acceptance",
        argNames: ["that", "chatId"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreCurrentInvitation(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreCurrentInvitationConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreCurrentInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_current_invitation",
        argNames: ["that", "chatId"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreDecryptText(
      {required CryptoCore that,
      required String chatId,
      required String blob}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_String(blob, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreDecryptTextConstMeta,
      argValues: [that, chatId, blob],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreDecryptTextConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_decrypt_text",
        argNames: ["that", "chatId", "blob"],
      );

  @override
  Future<void> crateApiCoreCryptoCoreDeleteChat(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreDeleteChatConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreDeleteChatConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_delete_chat",
        argNames: ["that", "chatId"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreEncryptText(
      {required CryptoCore that,
      required String chatId,
      required String text}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_String(text, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreEncryptTextConstMeta,
      argValues: [that, chatId, text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreEncryptTextConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_encrypt_text",
        argNames: ["that", "chatId", "text"],
      );

  @override
  Future<bool> crateApiCoreCryptoCoreIsVerified(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreIsVerifiedConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreIsVerifiedConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_is_verified",
        argNames: ["that", "chatId"],
      );

  @override
  Future<void> crateApiCoreCryptoCoreMarkVerified(
      {required CryptoCore that,
      required String chatId,
      required bool verified}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        sse_encode_bool(verified, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreMarkVerifiedConstMeta,
      argValues: [that, chatId, verified],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreMarkVerifiedConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_mark_verified",
        argNames: ["that", "chatId", "verified"],
      );

  @override
  Future<Uint8List> crateApiCoreCryptoCoreOpenLocal(
      {required CryptoCore that, required List<int> blob}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_list_prim_u_8_loose(blob, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreOpenLocalConstMeta,
      argValues: [that, blob],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreOpenLocalConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_open_local",
        argNames: ["that", "blob"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreSafetyNumber(
      {required CryptoCore that, required String chatId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_String(chatId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreSafetyNumberConstMeta,
      argValues: [that, chatId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreSafetyNumberConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_safety_number",
        argNames: ["that", "chatId"],
      );

  @override
  Future<Uint8List> crateApiCoreCryptoCoreSealLocal(
      {required CryptoCore that, required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCryptoCoreSealLocalConstMeta,
      argValues: [that, bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreSealLocalConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_seal_local",
        argNames: ["that", "bytes"],
      );

  @override
  Future<String> crateApiCoreCryptoCoreStoreDir({required CryptoCore that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreCryptoCoreStoreDirConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCryptoCoreStoreDirConstMeta =>
      const TaskConstMeta(
        debugName: "CryptoCore_store_dir",
        argNames: ["that"],
      );

  @override
  void crateApiFilesFileJobCancel({required FileJob that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFilesFileJobCancelConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesFileJobCancelConstMeta => const TaskConstMeta(
        debugName: "FileJob_cancel",
        argNames: ["that"],
      );

  @override
  void crateApiFilesFileJobPause({required FileJob that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFilesFileJobPauseConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesFileJobPauseConstMeta => const TaskConstMeta(
        debugName: "FileJob_pause",
        argNames: ["that"],
      );

  @override
  void crateApiFilesFileJobResume({required FileJob that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFilesFileJobResumeConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesFileJobResumeConstMeta => const TaskConstMeta(
        debugName: "FileJob_resume",
        argNames: ["that"],
      );

  @override
  BlobType crateApiFormatsBlobTypeOf({required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_blob_type,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFormatsBlobTypeOfConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFormatsBlobTypeOfConstMeta => const TaskConstMeta(
        debugName: "blob_type_of",
        argNames: ["text"],
      );

  @override
  Future<String> crateApiHealthCoreVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHealthCoreVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHealthCoreVersionConstMeta => const TaskConstMeta(
        debugName: "core_version",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiCoreCreateStoreKey({required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreCreateStoreKeyConstMeta,
      argValues: [password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreCreateStoreKeyConstMeta => const TaskConstMeta(
        debugName: "create_store_key",
        argNames: ["password"],
      );

  @override
  Stream<FileProgress> crateApiFilesDecryptFile(
      {required CryptoCore core,
      required String password,
      required String input,
      required String output,
      required FileJob job}) {
    final sink = RustStreamSink<FileProgress>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            core, serializer);
        sse_encode_String(password, serializer);
        sse_encode_String(input, serializer);
        sse_encode_String(output, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
            job, serializer);
        sse_encode_StreamSink_file_progress_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFilesDecryptFileConstMeta,
      argValues: [core, password, input, output, job, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFilesDecryptFileConstMeta => const TaskConstMeta(
        debugName: "decrypt_file",
        argNames: ["core", "password", "input", "output", "job", "sink"],
      );

  @override
  Stream<FileProgress> crateApiFilesEncryptFile(
      {required CryptoCore core,
      required String password,
      required String input,
      required String output,
      required FileJob job}) {
    final sink = RustStreamSink<FileProgress>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
            core, serializer);
        sse_encode_String(password, serializer);
        sse_encode_String(input, serializer);
        sse_encode_String(output, serializer);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
            job, serializer);
        sse_encode_StreamSink_file_progress_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFilesEncryptFileConstMeta,
      argValues: [core, password, input, output, job, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFilesEncryptFileConstMeta => const TaskConstMeta(
        debugName: "encrypt_file",
        argNames: ["core", "password", "input", "output", "job", "sink"],
      );

  @override
  Future<FileJob> crateApiFilesNewFileJob() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFilesNewFileJobConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesNewFileJobConstMeta => const TaskConstMeta(
        debugName: "new_file_job",
        argNames: [],
      );

  @override
  Future<CryptoCore> crateApiCoreOpenStore(
      {required String storeDir,
      required List<int> wrapped,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(storeDir, serializer);
        sse_encode_list_prim_u_8_loose(wrapped, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreOpenStoreConstMeta,
      argValues: [storeDir, wrapped, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreOpenStoreConstMeta => const TaskConstMeta(
        debugName: "open_store",
        argNames: ["storeDir", "wrapped", "password"],
      );

  @override
  String crateApiFormatsPeekChatId({required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiFormatsPeekChatIdConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFormatsPeekChatIdConstMeta => const TaskConstMeta(
        debugName: "peek_chat_id",
        argNames: ["text"],
      );

  @override
  Future<Uint8List> crateApiCoreRewrapStoreKey(
      {required List<int> wrapped,
      required String oldPassword,
      required String newPassword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(wrapped, serializer);
        sse_encode_String(oldPassword, serializer);
        sse_encode_String(newPassword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_core_error,
      ),
      constMeta: kCrateApiCoreRewrapStoreKeyConstMeta,
      argValues: [wrapped, oldPassword, newPassword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreRewrapStoreKeyConstMeta => const TaskConstMeta(
        debugName: "rewrap_store_key",
        argNames: ["wrapped", "oldPassword", "newPassword"],
      );

  @override
  Future<Uint8List> crateApiHealthRoundTrip({required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHealthRoundTripConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHealthRoundTripConstMeta => const TaskConstMeta(
        debugName: "round_trip",
        argNames: ["bytes"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CryptoCore => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CryptoCore => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FileJob => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FileJob => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  CryptoCore
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FileJob
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FileJobImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoCore
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoCore
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FileJob
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FileJobImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CryptoCore
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FileJob
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FileJobImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<FileProgress> dco_decode_StreamSink_file_progress_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlobType dco_decode_blob_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlobType.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatStatus dco_decode_chat_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatStatus.values[raw as int];
  }

  @protected
  CoreError dco_decode_core_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreError.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileProgress dco_decode_file_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FileProgress(
      progress: dco_decode_f_64(arr[0]),
      isComplete: dco_decode_bool(arr[1]),
      isCancelled: dco_decode_bool(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  CryptoCore
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FileJob
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FileJobImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CryptoCore
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CryptoCore
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FileJob
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FileJobImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CryptoCore
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CryptoCoreImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FileJob
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FileJobImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<FileProgress> sse_decode_StreamSink_file_progress_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlobType sse_decode_blob_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BlobType.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChatStatus sse_decode_chat_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ChatStatus.values[inner];
  }

  @protected
  CoreError sse_decode_core_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CoreError.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileProgress sse_decode_file_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_64(deserializer);
    var var_isComplete = sse_decode_bool(deserializer);
    var var_isCancelled = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return FileProgress(
        progress: var_progress,
        isComplete: var_isComplete,
        isCancelled: var_isCancelled,
        errorMessage: var_errorMessage);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          CryptoCore self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoCoreImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          FileJob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FileJobImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          CryptoCore self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoCoreImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          CryptoCore self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoCoreImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          FileJob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FileJobImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoCore(
          CryptoCore self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CryptoCoreImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFileJob(
          FileJob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FileJobImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_StreamSink_file_progress_Sse(
      RustStreamSink<FileProgress> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_file_progress,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_blob_type(BlobType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chat_status(ChatStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_core_error(CoreError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_progress(FileProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.progress, serializer);
    sse_encode_bool(self.isComplete, serializer);
    sse_encode_bool(self.isCancelled, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CryptoCoreImpl extends RustOpaque implements CryptoCore {
  // Not to be used by end users
  CryptoCoreImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CryptoCoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: FuzzyCryptoCoreLib
        .instance.api.rust_arc_increment_strong_count_CryptoCore,
    rustArcDecrementStrongCount: FuzzyCryptoCoreLib
        .instance.api.rust_arc_decrement_strong_count_CryptoCore,
    rustArcDecrementStrongCountPtr: FuzzyCryptoCoreLib
        .instance.api.rust_arc_decrement_strong_count_CryptoCorePtr,
  );

  /// B (accepter): verifies A's invitation, establishes the outbound session
  /// on its one-time key and returns the signed acceptance as `Fuzz/` text.
  /// `chat_id` must be the one inside the invitation (`WrongChat` otherwise);
  /// a chat that already has state is `Internal`.
  Future<String> acceptInvitation(
          {required String chatId, required String invitation}) =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreAcceptInvitation(
          that: this, chatId: chatId, invitation: invitation);

  /// `Connected` once this side holds a session, `Invited` before.
  Future<ChatStatus> chatStatus({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreChatStatus(that: this, chatId: chatId);

  /// Drops the store key and every cached state (all zeroised on drop).
  Future<void> close() =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreClose(
        that: this,
      );

  /// A (inviter): verifies B's acceptance and completes the handshake —
  /// the one-time key is consumed exactly once, so a second acceptance for
  /// the same invitation is `InvitationAlreadyUsed`. The session is on disk
  /// before this returns; any failure leaves the chat untouched.
  Future<void> completeHandshake(
          {required String chatId, required String acceptance}) =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreCompleteHandshake(
          that: this, chatId: chatId, acceptance: acceptance);

  /// A (inviter): creates the chat's Olm account and returns the signed
  /// invitation as `Fuzz/` text. Calling it again for a pending chat
  /// **regenerates** — a brand-new account replaces the old one, so the old
  /// invitation can no longer be completed. A connected chat is `Internal`.
  Future<String> createInvitation({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreCreateInvitation(that: this, chatId: chatId);

  /// The acceptance this chat last produced, for re-display.
  Future<String> currentAcceptance({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreCurrentAcceptance(that: this, chatId: chatId);

  /// The invitation this chat last produced, for re-display.
  Future<String> currentInvitation({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreCurrentInvitation(that: this, chatId: chatId);

  /// Decrypts a pasted message blob against `chat_id`'s session, checking the
  /// inner header and the replay/ordering window in the fixed order of plan
  /// §B.4. On any failure nothing is persisted — the state file is untouched,
  /// so the message key stays available for a re-paste (plan §B.6). Replay →
  /// `Replay`, a gap beyond Olm's window → `TooOld`, a blob for another chat or
  /// with the wrong identities → `WrongChat`, anything malformed → `Corrupt`.
  Future<String> decryptText({required String chatId, required String blob}) =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreDecryptText(
          that: this, chatId: chatId, blob: blob);

  /// Overwrites the chat's state file with zeros (best effort), unlinks it
  /// and forgets the cached state.
  Future<void> deleteChat({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreDeleteChat(that: this, chatId: chatId);

  /// Encrypts `text` on `chat_id`'s live Olm session and returns the `Fuzz/`
  /// message blob. The ratcheted session and the incremented send counter are
  /// persisted before the blob is returned, so a counter is never reused even
  /// across a crash. A chat that is not connected is `Internal`; an unknown
  /// chat id is `UnknownChat`.
  Future<String> encryptText({required String chatId, required String text}) =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreEncryptText(
          that: this, chatId: chatId, text: text);

  /// The persisted flag; `false` for every chat until [`CryptoCore::mark_verified`].
  Future<bool> isVerified({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreIsVerified(that: this, chatId: chatId);

  /// Persists whether the user compared the safety number with the peer. The
  /// flag is on disk before this returns; a chat that is not paired yet is
  /// `UnknownChat`.
  Future<void> markVerified({required String chatId, required bool verified}) =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreMarkVerified(
          that: this, chatId: chatId, verified: verified);

  /// Inverse of [`CryptoCore::seal_local`]; a tampered or foreign blob is `Corrupt`.
  Future<Uint8List> openLocal({required List<int> blob}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreOpenLocal(that: this, blob: blob);

  /// The chat's 60-digit safety number (`"12345 67890 …"`, 12 groups), derived
  /// from both Ed25519 identity keys and the chat id (plan §B.3) — identical on
  /// both sides of a pairing. `UnknownChat` for a chat the store does not know
  /// or that is not paired yet. Nothing secret is involved; it stays async
  /// like every other call on the handle.
  Future<String> safetyNumber({required String chatId}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreSafetyNumber(that: this, chatId: chatId);

  /// Seals `bytes` for local storage (message history, F2-8) under the
  /// HKDF-derived local key: a 0x20 blob with a fresh random nonce.
  Future<Uint8List> sealLocal({required List<int> bytes}) =>
      FuzzyCryptoCoreLib.instance.api
          .crateApiCoreCryptoCoreSealLocal(that: this, bytes: bytes);

  /// The directory the store was opened with (for tests).
  Future<String> storeDir() =>
      FuzzyCryptoCoreLib.instance.api.crateApiCoreCryptoCoreStoreDir(
        that: this,
      );
}

@sealed
class FileJobImpl extends RustOpaque implements FileJob {
  // Not to be used by end users
  FileJobImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FileJobImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        FuzzyCryptoCoreLib.instance.api.rust_arc_increment_strong_count_FileJob,
    rustArcDecrementStrongCount:
        FuzzyCryptoCoreLib.instance.api.rust_arc_decrement_strong_count_FileJob,
    rustArcDecrementStrongCountPtr: FuzzyCryptoCoreLib
        .instance.api.rust_arc_decrement_strong_count_FileJobPtr,
  );

  /// Terminal: the loop unlinks `<output>.part` and emits `is_cancelled` at
  /// the next chunk boundary (also while paused).
  void cancel() => FuzzyCryptoCoreLib.instance.api.crateApiFilesFileJobCancel(
        that: this,
      );

  /// The loop finishes the chunk in flight, then sleeps 50 ms at a time until
  /// [`FileJob::resume`] or [`FileJob::cancel`].
  void pause() => FuzzyCryptoCoreLib.instance.api.crateApiFilesFileJobPause(
        that: this,
      );

  /// Continues a paused job at the next chunk boundary; a no-op otherwise.
  void resume() => FuzzyCryptoCoreLib.instance.api.crateApiFilesFileJobResume(
        that: this,
      );
}
